edition                  = "2021"    # Rust edition
newline_style            = "Unix"    # never allow Windows' \n\r newlines

use_field_init_shorthand = true      # replace Foo { x: x } with Foo { x }
use_try_shorthand        = true      # replace try! with ?