[package]
name = "constraint_writers"
version = "2.1.8"
authors = ["Costa Group UCM","iden3"]
edition = "2018"

[dependencies]
circom_algebra = { path = "../circom_algebra" }
json = "0.12.4"
virtual_fs = { path = "../virtual_fs" }
