[package]
name = "circom_algebra"
version = "2.1.4"
authors = ["Costa Group UCM","iden3"]
edition = "2018"

[dependencies]
num-bigint-dig = "0.6.0"
num-traits = "0.2.6"
constant_tracking = {path = "../constant_tracking" }
