pub use custom_gate_analysis::custom_gate_analysis;
pub use functions_all_paths_with_return_statement::all_paths_with_return_check;
pub use functions_free_of_template_elements::free_of_template_elements;
pub use no_returns_in_template::free_of_returns;
pub use signal_declaration_analysis::check_signal_correctness;
pub use symbol_analysis::check_naming_correctness;
pub use type_check::type_check;
pub use unknown_known_analysis::unknown_known_analysis;

pub mod custom_gate_analysis;
pub mod functions_all_paths_with_return_statement;
pub mod functions_free_of_template_elements;
pub mod no_returns_in_template;
pub mod signal_declaration_analysis;
pub mod symbol_analysis;
pub mod type_check;
pub mod type_given_function;
pub mod type_register;
pub mod unknown_known_analysis;
