site_name: Circom 2 Documentation
site_url: https://iden3.github.io/circom/
theme:
     name: material
     palette:
          primary: blue
     # logo: assets/logo.png
     # favicon: images/favicon.png
     features:
          - navigation.tabs
          - navigation.tabs.sticky
          - navigation.tracking
repo_url: https://github.com/iden3/circom
markdown_extensions:
     - pymdownx.arithmatex:
          generic: true
extra_javascript:
     - javascripts/mathjax.js
     - https://polyfill.io/v3/polyfill.min.js?features=es6
     - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
     social:
          - icon: fontawesome/brands/telegram
            link: https://t.me/iden3io
          - icon: fontawesome/brands/github
            link: https://github.com/iden3/circom
          - icon: octicons/browser-24
            link: https://iden3.io/circom

nav:
     - Getting started:
          - Installation: 'getting-started/installation.md'
          - Writing circuits: 'getting-started/writing-circuits.md'
          - Compiling circuits: 'getting-started/compiling-circuits.md'
          - Computing the witness: 'getting-started/computing-the-witness.md'
          # - Testing circuits: 'getting-started/testing-circuits.md'
          - Proving circuits with ZK: 'getting-started/proving-circuits.md'
     - Background in ZK: 'background/background.md'
     - The circom Language:
          - Signals:
               - Signals: 'circom-language/signals.md'
               - Variables & Mutability: 'circom-language/variables-and-mutability.md'
          - Templates:
               - Templates & Components: 'circom-language/templates-and-components.md'
               - Pragma: 'circom-language/pragma.md'
               - Functions: 'circom-language/functions.md'
               - Include: 'circom-language/include.md'
               - The main Component: 'circom-language/the-main-component.md'
          - Syntax:
               - Comment Lines: 'circom-language/comment-lines.md'
               - Identifiers: 'circom-language/identifiers.md'
               - Reserved-keywords: 'circom-language/reserved-keywords.md'
          - Basic Operators: 'circom-language/basic-operators.md'
          - Constraint Generation: 'circom-language/constraint-generation.md'
          - Control Flow: 'circom-language/control-flow.md'
          - Data Types: 'circom-language/data-types.md'
          - Scoping: 'circom-language/scoping.md'
          - New features circom 2.1: 
               - Anonymous Components and tuples: 'circom-language/anonymous-components-and-tuples.md'
               - Tags: 'circom-language/tags.md'
          - Code Quality:
               - Code Assertion: 'circom-language/code-quality/code-assertion.md'
               - Debugging Operations: 'circom-language/code-quality/debugging-operations.md'
               - Inspect Option: 'circom-language/code-quality/inspect.md'
          - Circom Insight:
               - Compiler Phases: 'circom-language/circom-insight/circom-phases.md'
               - Compiler Messages: 'circom-language/circom-insight/compiler-messages.md'
               - Unknowns : 'circom-language/circom-insight/unknowns.md'
               - Circom Library: 'circom-language/circom-insight/circom-library.md'
     - More circuits: 
          - Basic circuits: 'more-circuits/more-basic-circuits.md'
     - Downloads: 'downloads/downloads.md'
